name: Test

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: Environment in double quotes, e.g. "development"
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/_reusable_test.yml
    with:
      environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: ${{ inputs.environment && fromJSON(format('["{0}"]', inputs.environment)) || [development, staging, production] }}
    secrets: inherit
